### ISSUE TITLE
is there a knowledge graph?

### ISSUE THREAD

**Issue by croussey** [ICA-EGAD/RiC-CM#1]
**Describe your feedback**
I found the model very closed to a relational model not a knowledge graph one. 
Why a two n ary relation is not represented as an object property?
Instantiation has a specific meaning in computer science, thus this word should not be used in any computer science model. The instantiation is the link between an individual and its type. This relation is name relationType in your ontology.
The same for type, types are classes, thus all the class child of Thing class are types. I can not make a difference between a type, a categorie and a class for a computer science point of view.

**Reference**
A reference to the Entity, Attribute or Relation in RiC-CM you want to give feedback to. 
Please use the identifiers used in RiC-CM, eg. RiC-E01 for "Thing".

**Proposed change**
why not reusing some part of existing ontology or vocabulary for example skos:xl for all the name staff, prov for the activity and provenance. Time ontology for time and so one, use any of the W3C ontology. This will change the model and your model will be closer to a knowledge graph one.

**Diagrams**
If applicable, add a drawing or diagram to help explain your feedback.

**Additional context**

**Comment by florenceclavaud** [comment]
Dear @croussey, 

**Records in Contexts Conceptual Model 0.2 (RiC-CM 0.2)** [https://www.ica.org/sites/default/files/ric-cm-02_july2021_0.pdf](https://www.ica.org/sites/default/files/ric-cm-02_july2021_0.pdf) **is a high level, abstract, conceptual model**, not an ontology. 
It is an entity-relationship model as explained in its introduction.
The introduction, p. 1, also explains that RiC-CM is part of **Records in Contexts standard,** which **includes an OWL ontology**, RiC-O. RiC-O latest public version [https://www.ica.org/standards/RiC/ontology](https://www.ica.org/standards/RiC/ontology) is RiC-O 0.2, that conforms to RiC-CM 0.2. Its source files and other files can be found on GitHub, here: [https://github.com/ICA-EGAD/RiC-O](https://github.com/ICA-EGAD/RiC-O). You can create issues about RiC-O there.
Hope this is useful.

Florence Clavaud, executive member of ICA EGAD

**Comment by croussey** [comment]
All my comments concerne the ontology. I have opened the rdf file using protégé tool. The translation into an ontology of the relational model is not correct.

**Comment by florenceclavaud** [comment]
Please, as I said, **if your comments concern the ontology, do not create issues in the RiC-CM repo, but do so in the  RiC-O one**: [https://github.com/ICA-EGAD/RiC-O] (https://github.com/ICA-EGAD/RiC-O).
Here, I will just say a few words on your comments, that, as they are, concern several topics and, for some of them, are general:
- Instantiation is an entity in RiC-CM and a class in RiC-O. It has its definition, which makes it semantically and formally very different from what you mention, which is represented in RDF by the rdf:type object property.
- every entity defined in RiC-CM is a class in RiC-O, and every relation that is defined in RiC-CM is an object property in RiC-O. And there are more classes and object properties in RiC-O. On this topic, see [https://www.ica.org/standards/RiC/RiC-O_v0-2.html#fromRiCCM-to-RiCO](https://www.ica.org/standards/RiC/RiC-O_v0-2.html#fromRiCCM-to-RiCO)
- as concerns you other comments, please see [https://ica-egad.github.io/RiC-O/why-use-RiC-O.html](https://ica-egad.github.io/RiC-O/why-use-RiC-O.html). We wanted, first to provide appropriate, accurate, definitions of the world of archives, second, build a domain ontology. This does not mean that we ignore the other existing ontologies. RiC-O will be mapped to other ontologies (it is in our roadmap).

Best,

Florence Clavaud

**Comment by florenceclavaud** [comment]
I am closing this issue as we answered the question IMHO.
